services:
  # Google Cloud Datastore Emulator
  datastore:
    image: google/cloud-sdk:emulators
    ports:
      - "8393:8393"
    command: >
      gcloud beta emulators datastore start
      --host-port=0.0.0.0:8393
      --project=local-test-project
      --no-store-on-disk
